# permissions for end users to edit nfsvolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nfsvolume-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nfs-manager
    app.kubernetes.io/part-of: nfs-manager
    app.kubernetes.io/managed-by: kustomize
  name: nfsvolume-editor-role
rules:
- apiGroups:
  - nfs.kyma-project.io
  resources:
  - nfsvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nfs.kyma-project.io
  resources:
  - nfsvolumes/status
  verbs:
  - get
