# permissions for end users to view nfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nfs-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nfs-manager
    app.kubernetes.io/part-of: nfs-manager
    app.kubernetes.io/managed-by: kustomize
  name: nfs-viewer-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - nfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - nfs/status
  verbs:
  - get
